name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
      - run: echo "Hello Guys"
      - name: Print bye
      - run: echo "Anurup loves lgbtqia+"
      
